[package]
name = "my-project"
version = "0.1.0"
authors = ["runner"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
evalexpr = "8.1.0"
pathfinding = "4.1.1"
regex = "1.7.0"
itertools = "0.8.0"